[workspace]
resolver = "2"
members = [
    "echo",
    "primes",
    "keystore",
    "chat",
    "db",
    "mob",
    "speed",
    "testing",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
debug = false
